"""v2_扩展日记模型_新增素材纪念日画像衍生表

Revision ID: fd6ad53a1082
Revises: 2782c58fdcd6
Create Date: 2026-03-25 15:03:00.444264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6ad53a1082'
down_revision: Union[str, None] = '2782c58fdcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('title', sa.String(), nullable=True))
    op.add_column('diaries', sa.Column('special_date', sa.String(), nullable=True))
    op.add_column('diaries', sa.Column('emotion_summary', sa.Text(), nullable=True))
    op.add_column('diaries', sa.Column('material_ids', sa.Text(), nullable=True))
    op.add_column('diaries', sa.Column('edit_count', sa.Integer(), nullable=True))
    op.add_column('diaries', sa.Column('max_edits', sa.Integer(), nullable=True))
    op.add_column('diaries', sa.Column('status', sa.String(), nullable=True))
    op.add_column('diaries', sa.Column('date', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('match_type', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('match_report', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('user_portrait_snapshot', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('openclaw_agent_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('style_tags', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('custom_style_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_style_prompt')
    op.drop_column('users', 'style_tags')
    op.drop_column('users', 'openclaw_agent_id')
    op.drop_column('matches', 'user_portrait_snapshot')
    op.drop_column('matches', 'match_report')
    op.drop_column('matches', 'match_type')
    op.drop_column('diaries', 'date')
    op.drop_column('diaries', 'status')
    op.drop_column('diaries', 'max_edits')
    op.drop_column('diaries', 'edit_count')
    op.drop_column('diaries', 'material_ids')
    op.drop_column('diaries', 'emotion_summary')
    op.drop_column('diaries', 'special_date')
    op.drop_column('diaries', 'title')
    # ### end Alembic commands ###
